version: "3"

services:
  minecraft:
    image: damyanyordanov/minecraft-java:1.20.1
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Yordanov Minecraft Server"
      MOTD: "Welcome to Julian Alex' Minecraft Server"
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 4096M
        reservations:
          memory: 1024M
    restart: unless-stopped
    volumes:
      - mc:/mc

volumes:
  mc: {}
